### PR TITLE
[Fix] properly determine length of rootValids for engine in isSame comparison

### PR DESCRIPTION
**Pull request by travi**
in attempting to understand why our newly added `ls-engines` checks were failing for https://github.com/semantic-release/npm/pull/402 and https://github.com/semantic-release/github/pull/412, i tracked down that the `graphValids` and `rootValids` were the same lists, but not being reported as such. 

i havent tracked down how to cover this gap in the tests yet, but wanted to get this much out here before calling it a (late) night. i'm happy to help get a test in place for this with a little guidance.

### CODE REVIEW

**Comment by ljharb** [comment]
woof, that’s an obvious bug. I’ll take a look this weekend and see if i can come up with tests.

**Comment by travi** [comment]
> I’ll take a look this weekend and see if i can come up with tests.

thanks for taking a look. having looked through the test suite, it does seem like you would be better suited to address the tests on this one, but let me know if it would be worth me digging deeper.

**Comment by ljharb** [comment]
I'll definitely take a crack at it before asking you to do more work :-) thanks!

**Review by ljharb — APPROVED** [review]
Thanks! I added tests, and will land and release this shortly.

**Comment by travi** [comment]
just getting back from vacation, so this was a great thing to come back to. thanks so much for taking care of this!

**Pull request merged**
